import '../styles/globals.scss'
import {Roboto} from 'next/font/google'

const roboto = Roboto({weight: ['400', '500', '700'], subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={roboto.className}>
    <main className={'container'}>
      {children}
    </main>
    </body>
    </html>
  )
}
